version: 2.1

parameters:
  image_name:
    type: string
    default: "quay.io/hmpps/prison-estate"
  app_name:
    type: string
    default: "prison-estate"

orbs:
  dps: ministryofjustice/dps@1.1.0
  owasp: entur/owasp@0.0.10

executors:
  validator:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      _JAVA_OPTIONS: -Xmx256m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-XX:+UseContainerSupport
    working_directory: ~/app

jobs:
  validate:
    executor: validator
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle.kts

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - dps/build_docker:
          name: build_docker
          image_name: << pipeline.parameters.image_name >>
          filters:
            branches:
              only:
                - master
      - dps/deploy_env:
          name: deploy_dev
          env: "dev"
          app_name: << pipeline.parameters.app_name >>
          filters:
            branches:
              only:
                - master
          requires:
            - validate
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - dps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          app_name: << pipeline.parameters.app_name >>
          context: prison-estate-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - dps/deploy_env:
          name: deploy_prod
          env: "prod"
          app_name: << pipeline.parameters.app_name >>
          slack_notification: true
          context: prison-estate-prod
          requires:
            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - owasp/gradle_owasp_dependency_check:
          executor: validator
