# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/prison-estate
  tag: latest
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: estate.prison.service.justice.gov.uk
      cert_secret: prison-estate-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
